# Generated by Django 2.1.7 on 2019-04-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='latitude',
            field=models.DecimalField(decimal_places=13, max_digits=15),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='longitude',
            field=models.DecimalField(decimal_places=13, max_digits=15),
        ),
    ]
