# Generated by Django 2.1.7 on 2019-04-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190413_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
